# Generated by Django 5.0.1 on 2025-10-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('legajo', models.CharField(max_length=50, unique=True)),
                ('docenteId', models.ForeignKey(blank=True, db_column='docenteId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'estudiantes',
                'ordering': ['id'],
            },
        ),
    ]
