# Generated by Django 5.0.1 on 2025-10-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('permisos', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('legajo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField()),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
    ]
