# Generated by Django 5.0.1 on 2025-10-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50)),
                ('horas_semanales', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocenteMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField(default=2)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.usuario')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion_academica.materia')),
            ],
            options={
                'db_table': 'asignaciones_docentes_materias',
                'ordering': ['id'],
                'unique_together': {('id_usuario', 'id_materia')},
            },
        ),
    ]
