# Generated by Django 5.2.6 on 2025-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocenteMateria',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField()),
                ('id_materia', models.IntegerField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Activa', max_length=50)),
            ],
            options={
                'db_table': 'asignaciones_docentes_materias',
            },
        ),
    ]
