# Generated by Django 5.2.6 on 2025-10-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
